---
title: "Stat346_HW2"
author: "Jack Forrest and Jianing Ren"
date: "20/09/2020"
output: html_document
---

## 1 Equivalent Expression.
### a. Show that these are equivalent. $b_1 = \frac{\sum{(x_i-\bar{x})(y_i-\bar{y})}}{\sum{(x_i-\bar{x})^2}}$; $b_1 = \dfrac{\sum{x_iy_i}-n\bar{x}\bar{y}}{\sum{x_i^2}-n\bar{x}^2}$

Expand from the first equation, we get:
$$
\begin{aligned}
b_1 &= \frac{\sum{(x_i-\bar{x})(y_i-\bar{y})}}{\sum{(x_i-\bar{x})^2}}\\
&=\frac{\sum{(x_iy_i-x_i\bar{y}-\bar{x}y_i+\bar{x}\bar{y})}}{\sum{(x_i^2-2x_i\bar{x}+\bar{x}^2)}}\\
\end{aligned}
$$

Breaking up the summation and factoring out the constants, we get:
$$b_1=\frac{\sum{x_iy_i}-n\bar{y}\sum{x_i}-n\bar{x}\sum{y_i}+n{\bar{x}\bar{y}}}{\sum{x_i^2}-2n\bar{x}\sum{x_i}+n\bar{x}^2}$$

After manipulating the $\sum{x_i}$ or $\sum{y_i}$ terms by multiplying top and bottom by n, we get: 
$$b_1=\frac{\sum{(x_iy_i)}-n\bar{y}\bar{x}-n\bar{x}\bar{y}+n\bar{x}\bar{y}}{\sum{x_i^2}-2n\bar{x}\bar{x}+n\bar{x}^2}=\dfrac{\sum{x_iy_i}-n\bar{x}\bar{y}}{\sum{x_i^2}-n\bar{x}^2}$$. 

### b. Show that we can also write this as $b_1 = \frac{\sum{(x_i-\bar{x})y_i}}{\sum{(x_i-\bar{x})^2}} = \sum{k_i y_i}$

We can first transform b1's numerator, $\sum{(x_i-\bar{x})(y_i-\bar{y})}$, into:
$$\begin{aligned}
\sum{(x_i-\bar{x})(y_i-\bar{y})} &= \sum{(x_i-\bar{x})y_i}-\sum{(x_i-\bar{x})\bar{y}}\\ 
&= \sum{(x_i-\bar{x})y_i}-\bar{y}\sum{(x_i-\bar{x})}.
\end{aligned}$$ 

Note that residuals sum to zero by definition, so $\sum{(x_i-\bar{x})}=0$. Therefore the numerator for $b_1$ is $\\sum{(x_i-\bar{x})y_i}$. Putting the numerator back to $b_1$, we get $$b_1=\frac{\sum{(x_i-\bar{x})y_i}}{\sum{(x_i-\bar{x})^2}} = \sum{k_i y_i},$$ where $$k_i =  \dfrac{(x_i-\bar{x})}{S_{xx}}$$

### c. What does that say about which observations have the most influence in the slope estimate? In particular, what about a $y_i$ whose $x$ value is at the $x$-mean? 

Since $b_1$ is a weighted average of $y_i$, an outlier in the y axis is going to influence the slope, but only if its $x_i \neq \bar{x}$ (more on that later). 

Since $k_i$ also depends on $x_i$, a point with large $x_i$ (i.e., a point with high "leverage") will have heavy influence on $b_1$, but only if its y value is away from the line as well. 

Additionally, for an observation whose $x_i=\bar{x}$, we know that its $k_i$ must equal to zero, therefore having that observation has no influence on the calculation of $b_i$ (basically a term of zero is added to the summation). Thus, adding a point whose $x_i=\bar{x}$ will not change the slope; only the intercept will be changed if its $y_i \neq \bar{y}$. 

## 2 **Pick a card, any card** You draw a card from a deck. If you get a red card, you win nothing. If you get a spade, you win \$5. For any club other than the ace, you win \$10. You win \$30 for the ace of clubs.

### a. Create a probability model for the amount you win.

Let X be a random variable representing the amount you will win in the game. 

Hearts and diamonds: x=0, P(0)=26/52

Spades: x=5, P(5)=13/52

Clubs other than ace: x=10, P(10)=12/52

Ace of clubs: x=30, P(30)=1/52

QUESTION: P vs p, X vs x in the context? does P(X=5) mean the probability of winning 5 dollars? 

### b. Find the expected amount you’ll win (*i.e* the fair worth of the game)
$$\begin{aligned}
E(X)&=\sum{xp(x)}\\
&=0*\frac{26}{52}+5*\frac{13}{52}+10*\frac{12}{52}+30*\frac{1}{52}\\
&=\frac{215}{52}\\
&\approx4.13\\
\end{aligned}
$$

### c. Find the standard deviation for amount you'll win.
$$\begin{aligned}
Var(X)&=\sum{(x-\mu)^2P(x)}\\
&=(0-4.13)^2(\frac{26}{52})+(5-4.13)^2(\frac{13}{52})+(10-4.13)^2(\frac{12}{52})+(30-4.13)^2(\frac{1}{52})\\
&\approx29.54\\
\end{aligned}
$$

## 3 **An *n* sided die** Let $Y$ be the number showing after tossing an *n* sided die. In other words, $Y$ is a uniform random variable  on the integers $\{1,2,\dots,n\}$. Using the facts that $\sum_{i=1}^n i= \frac{n (n+1)}{2}$ and $\sum_{i=1}^n i^2 = \frac{n(n+1)(2n+1)}{6}$, find

### a. The expected value of $Y$

$$\begin{aligned}
E(Y)&=\sum{yp(y)}\\
&=\sum_{i=1}^n{\frac{1}{n}i}\\
&=\frac{1}{n}\sum{i}\\
&=\frac{n+1}{2}
\end{aligned}$$

### b. Its standard deviation
$$
\begin{aligned}
Var(Y)&=E(Y^2)-(E(Y))^2\\
&=\frac{1}{n}\sum{i^2}-(\frac{n+1}{2})^2\\
&=\frac{(n+1)(2n+1)}{6}-\frac{n^2+2n+1}{4}\\
&=\frac{(4n+2)(n+1)-(3n+3)(n+1)}{12}\\
&=\frac{n^2-1}{12}
\end{aligned}
$$

### c. Simulate 100,000 tosses of a 6 sided die and show that the mean and sd of the tosses matches (at least approximately) what you showed in parts a) and b).

```{r}
suppressMessages(library(mosaic))
toss=sample(c(1:6),100000,replace = T)
mean(toss) #simulated mean
var(toss) #simulated var

(6+1)/2 #theoratical mean
(6^2-1)/12 #theoratical var
```

## 4. **Continuous Uniform** Now let $Y$ be a *continuous* uniform random variable on $[a,b]$. In other words, 
$$f(y) =  \begin{cases} \frac{1}{b-a} &\mbox{if} ~~~a \le x \le b \\ 
0 & \mbox{otherwise}\end{cases}$$

### a. Find $E(Y)$

$$
\begin{align}
E(Y)&=\sum{xp(x)}\\
&=\frac{1}{b-a}\sum_{i-a}^bi\\

\end{align}
$$

Note that i is continuous on [a,b], therefore we can write it as an integral:

$$
\begin{align}
&=\frac{1}{b-a}\int_a^bxdx\\
&=\frac{b^2-a^2}{2(b-a)}\\
&=\frac{(b-a)(b+a)}{2(b-a)}\\
&=\frac{b+a}{2}
\end{align}
$$

### b. Find $\sigma_Y$ Hint: Use $Var(Y) = E(Y^2) - \mu^2$.
$$
\begin{align}
Var(Y)&=E(Y^2)-\mu^2\\
&=\sum_{i=a}^b i^2 p(y) - \mu^2\\
&=\frac{1}{b-a}\int_{a}^b x^2 dx-\frac{(a+b)^2}{4}\\
&=\frac{1}{b-a}\frac{b^3-a^3}{3}-\frac{(a+b)^2}{4}\\
&=\frac{b^2+ab+a^2}{3}-\frac{a^2+2ab+b^2}{4}\\
&=\frac{(a-b)^2}{12}\\\\
\sigma(Y)&=\sqrt{Var(Y)}\\
&=\frac{a-b}{2\sqrt3}
\end{align}
$$